
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "quantum-rag-ingestion-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "infinity-x-one-systems"
  location                      = "us-central1"
  service_name                  = "quantum-rag-ingestion-service"
  containers                    = [{"ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = {"quantum_rag_data_processing_topic_TOPIC_ID" = module.quantum-rag-data-processing-topic.id}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-data-bucket" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.0.0"
  project_id = "infinity-x-one-systems"
  location   = "us-central1"
  name       = "quantum-rag-data-bucket"
  iam_members = [{
    member = module.quantum-rag-ingestion-service.service_account_id.member
    role   = "roles/storage.objectAdmin"
  }]
  storage_class = "STANDARD"
  depends_on    = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-data-processing-topic" {
  source             = "github.com/terraform-google-modules/terraform-google-pubsub?ref=v8.3.2"
  project_id         = "infinity-x-one-systems"
  topic              = "quantum-rag-data-processing-topic"
  push_subscriptions = concat([{"name" = module.quantum-rag-ingestion-service.apphub_service_uri.service_id, "oidc_service_account_email" = module.quantum-rag-ingestion-service.service_account_id.email, "push_endpoint" = module.quantum-rag-ingestion-service.service_uri}], [{"name" = module.quantum-rag-data-processor.apphub_service_uri.service_id, "oidc_service_account_email" = module.quantum-rag-data-processor.service_account_id.email, "push_endpoint" = module.quantum-rag-data-processor.service_uri}])
  pull_subscriptions = concat([{"service_account" = module.quantum-rag-ingestion-service.service_account_id.email, "name" = module.quantum-rag-ingestion-service.service_name}], [{"name" = module.quantum-rag-data-processor.service_name, "service_account" = module.quantum-rag-data-processor.service_account_id.email}])
  depends_on         = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-data-processor" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "infinity-x-one-systems"
  location                      = "us-central1"
  service_name                  = "quantum-rag-ingestion-service"
  containers                    = [{"container_name" = "service-container", "env_secret_vars" = {"quantum_rag_database_secret_SECRET" = module.quantum-rag-database-secret.env_vars.SECRET}, "env_vars" = merge({"quantum_rag_data_processing_topic_TOPIC_ID" = module.quantum-rag-data-processing-topic.id}, {"quantum_rag_database_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.quantum-rag-database.instance_connection_name, "quantum_rag_database_CLOUD_SQL_DATABASE_HOST" = module.quantum-rag-database.instance_first_ip_address, "quantum_rag_database_CLOUD_SQL_DATABASE_NAME" = module.quantum-rag-database.env_vars.CLOUD_SQL_DATABASE_NAME}), "ports" = {"container_port" = 8080}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"], ["roles/aiplatform.user"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    quantum_rag_vertex_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-vertex-apis" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "infinity-x-one-systems"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-database" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "infinity-x-one-systems"
  region                      = "us-central1"
  name                        = "quantum-rag-database"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users  = concat([{"email" = module.quantum-rag-data-processor.service_account_id.email, "id" = module.quantum-rag-data-processor.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}], [{"email" = module.quantum-ai-serving-backend-service.service_account_id.email, "id" = module.quantum-ai-serving-backend-service.service_account_id.id, "type" = "CLOUD_IAM_SERVICE_ACCOUNT"}])
  depends_on = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-rag-database-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "infinity-x-one-systems"
  name        = "quantum-rag-database-secret"
  secret_data = module.quantum-rag-database.generated_user_password
  depends_on  = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-ai-serving-backend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = "infinity-x-one-systems"
  location                      = "us-central1"
  service_name                  = "quantum-ai-serving-backend-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = {"quantum_rag_database_CLOUD_SQL_DATABASE_NAME" = module.quantum-rag-database.env_vars.CLOUD_SQL_DATABASE_NAME, "quantum_rag_database_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.quantum-rag-database.instance_connection_name, "quantum_rag_database_CLOUD_SQL_DATABASE_HOST" = module.quantum-rag-database.instance_first_ip_address}, "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/aiplatform.user"], ["roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    quantum_ai_serving_vertex_ai_apis_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "quantum-ai-serving-vertex-ai-apis" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "infinity-x-one-systems"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-infinity-x-one-systems, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.quantum-rag-ingestion-service.apphub_service_uri], [module.quantum-rag-data-bucket.apphub_service_uri], [module.quantum-rag-data-processor.apphub_service_uri], [module.quantum-rag-database.apphub_service_uri], [module.quantum-ai-serving-backend-service.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-infinity-x-one-systems" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "infinity-x-one-systems"
  disable_services_on_destroy = false
  activate_apis               = []
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "infinity-x-one-systems"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudresourcemanager.googleapis.com"]
}
