
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "quantum-rag-ingestion-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.quantum-rag-ingestion-service.service_uri
}
output "quantum-rag-data-processor_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.quantum-rag-data-processor.service_uri
}
output "quantum-ai-serving-backend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.quantum-ai-serving-backend-service.service_uri
}
